import React from 'react'

const NewSendOrder = () => {
  return (
    <div>
      <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eveniet pariatur repellendus ipsum sunt cum possimus provident facilis aliquid modi totam debitis, quasi eum placeat odio at nihil mollitia? Culpa dicta accusantium explicabo optio reprehenderit dolore architecto vitae sit laudantium autem, modi totam quis rem, repellat commodi delectus maxime debitis voluptatum? Distinctio, officia natus culpa eveniet facere quibusdam rerum doloribus quidem assumenda laborum ipsum id dignissimos repellat aliquid magnam? Dolore facere temporibus reprehenderit? Excepturi, atque asperiores, exercitationem officiis quo fugit accusamus ratione architecto, odit mollitia commodi cum eaque fuga ad perferendis vel facilis? Totam officiis aut iusto sunt quaerat dolorem ipsam nisi repudiandae, sapiente iure magnam eaque. Animi repudiandae dolore, tempore ex quidem excepturi. Minima beatae, voluptatibus ab eligendi tempore delectus corporis necessitatibus quia quisquam aut at saepe hic maxime cumque aperiam, suscipit iure impedit aspernatur minus a, commodi consequatur? Quaerat illum omnis distinctio fugiat commodi labore aut ut, modi tempora suscipit ea accusantium praesentium reiciendis maxime atque. Nihil, temporibus doloribus. Corrupti alias labore praesentium veritatis! Enim et facilis cum ut, repudiandae, quas consectetur nostrum debitis, fuga voluptatum adipisci. Sapiente porro sit inventore esse provident eaque quos, maiores repellendus non nihil suscipit libero consequatur voluptates sint blanditiis dolorem accusantium placeat aut dolores deleniti odit. Ad illo quidem neque deleniti ipsam qui laborum dolor sapiente ex enim impedit, animi repudiandae rem temporibus, quae reiciendis suscipit id labore! Velit ipsum qui vitae cumque provident id saepe, dolorem minima est blanditiis quam magni optio aliquid, animi eos impedit beatae? Harum possimus accusantium non porro? Optio, et. Quod repudiandae iure magnam cumque quis, porro animi adipisci distinctio. Voluptas ullam et nobis laborum saepe fugit nulla suscipit quibusdam quos, exercitationem sapiente soluta impedit quisquam? Id ex velit odio tempora, molestias facere saepe dolores consectetur, eaque illum sequi maiores nostrum quia suscipit. Minima enim hic doloribus quos!</p>
    </div>
  )
}

export default NewSendOrder
